import type { Metadata } from "next";
import Navbar from "@/src/components/Navbar";
import Footer from "@/src/components/Footer";

export const metadata: Metadata = {
  title: "Car Rental | Dubai",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicon-removebg-preview.ico" }],
    shortcut: "/shortcut-icon.png",
    apple: "/apple-icon.png",
  },
};

export default function PublicLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
