import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/src/components/Navbar";
import Footer from "@/src/components/Footer";
const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Car Rental | Dubai",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicon-removebg-preview.ico" }], // Simple path relative to the public folder
    shortcut: "/shortcut-icon.png",
    apple: "/apple-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
